/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo;

import org.junit.Test;
 
import gradle.demo.Employee;
 
import static org.junit.Assert.*;
 
public class EmployeeTest {
 
    @Test
    public void mySimpleEqualsTest(){
         
        String expectedName = "Nattu";
        assertEquals(expectedName, Employee.getEmpNameWithHighestSalary());
    }
     
    @Test
    public void myObjectEqualsTest(){
         
        Employee expectedEmpObj = new Employee(1, "Nattu", 15000);
        assertEquals(expectedEmpObj, Employee.getHighestPaidEmployee());
    }
}